#!/usr/bin/env bash
# Install nginx

apt-get -y update
apt-get -y install nginx

ufw allow 'Nginx HTTP'
sed -i -e 's/a listen */a 80/g''s/a root */a /var/www/html/index.nginx-debian.html' /etc/nginx/sites-enabled/default
echo "Hello World" > /var/www/html/index.nginx-debian.html

sudo service nginx restart
