#!/usr/bin/env bash
#This script will configure Nginx so that its HTTP response contains a custom header

nginx -v >/dev/null 2>&1
if [[ $? -ne 0 ]]; then
	sudo apt update
	sudo apt install nginx
fi
sudo systemctl start nginx
