#!/usr/bin/env bash
# This script will debug a server

ln -sf /etc/nginx/nginx.conf /etc/nginx/sites-enabled/default
if sudo systemctl status nginx
then
	sudo systemctl start nginx.service
elif sudo lsof -i :80 -s TCP:LISTEN
then
	sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
fi
sed "s/ipv4only=on"
sudo service nginx restart
