#!/usr/bin/env bash
# This script will debug a server

if sudo systemctl status nginx
	sudo systemctl start nginx.service
else if sudo lsof -i :80 -s TCP:LISTEN
	sed 's/listen +$ 8080/ 80/'
	sed 's/listen [::] +$8080/ 80/'
fi
service nginx restart

