#!/usr/bin/env bash
# This script will debug a server

if sudo systemctl status nginx
then
	sudo systemctl start nginx.service
elif sudo lsof -i :80 -s TCP:LISTEN
then
	sed -i 's/8080/80/g' /etc/nginx/conf. d
fi
sed "s/listen +$ /ipv4only=on"
sudo service nginx restart
