#!/usr/bin/env bash
#This script will do Fizzbuzz

i=1
while [ $i -le 100 ]
do
	fizz=$((i % 3))
	buzz=$((i % 5))
	if [ $fizz -eq 0 ]
	then
		if [ $buzz -eq 0 ]
		then
			echo "FizzBuzz"
		else
			echo "Fizz"
		fi
	elif [ $buzz -eq 0 ]
	then
		echo "Buzz"
	else
		echo $i
	fi
	i=$((i + 1))
done
