#!/usr/bin/env bash
#This script will display 59 minutes and the hours for 12 hours

i=1

while [ $i -le 13 ]
do
	j=1
	while [ $j -le 59 ]
	do
		echo $j
		j=$(($j + 1))
	done
	if [ $i -lt 13 ]
	then
		echo "Hour: $i"
	fi
	i=$(($i + 1))
done
