#!/usr/bin/env bash
#This script will display tell if file exist

file="school"
if [ -e $file ]
then
	echo "school file exists"
	if [ -f $file ]
	then
		echo "school is a regular file"
	fi
	if [ -s $file ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
else
	echo "school file does not exist"
fi
