#!/usr/bin/env bash
#This script will configure an Ubuntu server
cp /etc/hosts ~/hosts.new
sed 's+157.240.11.35        facebook.com+8.8.8.8        facebook.com+g' ~/hosts.new
sed 's+127.0.0.1        localhost+127.0.0.2        localhost+g' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
