#!/usr/bin/env bash
#This script will configure an Ubuntu server
cp /etc/hosts ~/hosts.new
sed -i 's/157.240.11.35		facebook/8.8.8.8		facebook/g' ~/hosts.new
sed -i 's/127.*/127.0.0.2/g' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
