#!/usr/bin/env bash
# This script will configure an Ubuntu server

cp /etc/hosts ~/hosts.new
sed -i "s/^127.0.0.1$/127.0.0.2 localhost\n" ~/hosts.new
echo /hosts.new >> "8.8.8.8 facebook.com" ~/hosts.new
cp -f ~/hosts.new /etc/hosts

